<a href="https://colab.research.google.com/github/Varsha7330/colab/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perform arithmetic operations on NumPy arrays.


In [1]:
import numpy as np
a=np.array([4,5,6])
b=np.array([7,8,9])
print("Addition of array: ",a+b)
print("Subtraction of array: ",a-b)
print("Multiplication of array: ",a*b)
print("Division of array: ",a/b)


Addition of array:  [11 13 15]
Subtraction of array:  [-3 -3 -3]
Multiplication of array:  [28 40 54]
Division of array:  [0.57142857 0.625      0.66666667]


2.Write a script to compute the mean and standard deviation of NumPy array.


In [2]:
a=np.array([1,2,3,4,5])
print("Mean of array: ",np.mean(a))
print("Standard deviation of array: ",np.std(a))

Mean of array:  3.0
Standard deviation of array:  1.4142135623730951


3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [3]:
a=np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


4. Reshape the array into a 2x4 matrix.

In [4]:
matrix=a.reshape(2,4)
print(matrix)

[[10 15 20 25]
 [30 35 40 45]]


5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

• Extract the sub-matrix containing the last two rows and first two columns.

• Replace all elements greater than 4 with 0.

In [5]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
sub_matrix=a[1:,:2]
print(sub_matrix)
a[a>4]=0
print(a)

[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


6. Create two 1D arrays:

• a = np.array([1, 2, 3])

• b = np.array([4, 5, 6])

• Perform element-wise addition, multiplication, and division.

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition: ",a+b)
print("Multiplication: ",a*b)
print("Division: ",a/b)

Addition:  [5 7 9]
Multiplication:  [ 4 10 18]
Division:  [0.25 0.4  0.5 ]


7. Create a random NumPy array of size (4, 4). Compute:

• Mean of each column.

• Maximum value of the entire array.

• Sum of all elements.

In [9]:
a=np.random.rand(4,4)
print("Mean of each column: ",np.mean(a,axis=0))
print("Maximum value of the entire array: ",np.max(a))
print("Sum of all elements: ",np.sum(a))

Mean of each column:  [0.65787602 0.38400977 0.4801495  0.4683005 ]
Maximum value of the entire array:  0.9943000454654339
Sum of all elements:  7.96134317580907


8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [10]:
 arr = np.array([1, 2, 3, 4])
 result=2*(arr+10)
 print(result)


[22 24 26 28]


9. Perform advanced slicing and indexing on a 3D array.

Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from

1 to 100. Perform the following:

• Extract the second "layer" (i.e., the second 2D array) in the first dimension.

• Extract the first two rows and the last three columns from each "layer."

• Replace all elements divisible by 3 with -1.

In [11]:
a=np.random.randint(1,101,size=(3,4,5))
print(a)
print("Second layer: ",a[1])
print("First two rows and last three columns: ",a[:,:2,-3:])
a[a%3==0]=-1
print(a)

[[[ 27  32  13  45  32]
  [ 21  62  41  79   1]
  [ 60  42  61  59 100]
  [100  27  49  29  58]]

 [[ 95  30  58  17  18]
  [  1  23   3  64  33]
  [ 29   2  94  53  46]
  [ 47  79  56  70  31]]

 [[ 54   6  19  37  99]
  [ 84  49  17  70  66]
  [ 93  81  94  69  43]
  [  1  67  89  45  82]]]
Second layer:  [[95 30 58 17 18]
 [ 1 23  3 64 33]
 [29  2 94 53 46]
 [47 79 56 70 31]]
First two rows and last three columns:  [[[13 45 32]
  [41 79  1]]

 [[58 17 18]
  [ 3 64 33]]

 [[19 37 99]
  [17 70 66]]]
[[[ -1  32  13  -1  32]
  [ -1  62  41  79   1]
  [ -1  -1  61  59 100]
  [100  -1  49  29  58]]

 [[ 95  -1  58  17  -1]
  [  1  23  -1  64  -1]
  [ 29   2  94  53  46]
  [ 47  79  56  70  31]]

 [[ -1  -1  19  37  -1]
  [ -1  49  17  70  -1]
  [ -1  -1  94  -1  43]
  [  1  67  89  -1  82]]]


10. Work with broadcasting and advanced operations in NumPy.

Create a NumPy array arr of shape (3, 3) with random integers between  
1 and 20. Perform the following:

• Subtract the mean of each row from its respective elements (row-wise
normalization).

• Create a new array by squaring all the elements in arr.

• Find the indices of the top 3 maximum values in the entire array.

In [15]:
a=np.random.randint(1,21,size=(3,3))
print(a)
print("Row-wise normalization: ",a-a.mean(axis=1,keepdims=True))
print("New array: ",np.square(a))
indices=np.argsort(a.flatten())[-3:]
print("Indices of top 3 maximum values: ",indices)


[[10  1 16]
 [ 5  6  4]
 [ 9  4 19]]
Row-wise normalization:  [[ 1.         -8.          7.        ]
 [ 0.          1.         -1.        ]
 [-1.66666667 -6.66666667  8.33333333]]
New array:  [[100   1 256]
 [ 25  36  16]
 [ 81  16 361]]
Indices of top 3 maximum values:  [0 2 8]
